// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ8rgUsmUY6L69xqGTMb0aQtMIEkM8FZk',
    appId: '1:415829405138:web:abc3c104afce5c65d32c0b',
    messagingSenderId: '415829405138',
    projectId: 'sums-seguridad',
    authDomain: 'sums-seguridad.firebaseapp.com',
    storageBucket: 'sums-seguridad.firebasestorage.app',
    measurementId: 'G-ZYYGF7PTHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc72soWE57cF-UTaF0uNsSFjWozR3hRSM',
    appId: '1:415829405138:android:97e5eae7decaf0ddd32c0b',
    messagingSenderId: '415829405138',
    projectId: 'sums-seguridad',
    storageBucket: 'sums-seguridad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWWsuP4Xux-tnEsY0TMXk5iBU62Z56nw',
    appId: '1:415829405138:ios:926d76b72082b7aad32c0b',
    messagingSenderId: '415829405138',
    projectId: 'sums-seguridad',
    storageBucket: 'sums-seguridad.firebasestorage.app',
    iosBundleId: 'com.example.appmobileSecurity',
  );
}
